name: Package Python App for Multiple Platforms

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [windows-latest]
        include:
          #- os: ubuntu-latest
          #  output_name: od_convert_linux
          #- os: macos-latest
          #  output_name: od_convert_mac
          - os: windows-latest
            output_name: od_convert_windows
    
    runs-on: ${{ matrix.os }}
    #permissions:
     # contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build with PyInstaller
      run: |
        pyinstaller gui6.spec --distpath ./dist/${{ matrix.output_name }} --workpath ./build/${{ matrix.output_name }}
        pyinstaller gui6_single.spec --distpath ./dist/${{ matrix.output_name }}_exe --workpath ./build/${{ matrix.output_name }}_exe

    - name: Upload full distribution artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.output_name }}_full
        path: dist/${{ matrix.output_name }}/

    - name: Upload single executable artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.output_name }}_exe
        path: dist/${{ matrix.output_name }}_exe/
    - name: Zip full distribution
      run: |
        Compress-Archive -Path dist/${{ matrix.output_name }} -DestinationPath ${{ matrix.output_name }}_full.zip
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::Build_$(date +"%Y.%m.%d_%H-%M")"
    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{steps.tag.outputs.release_tag}}
        files: |
          dist/${{ matrix.output_name }}_exe/*.exe
          ${{ matrix.output_name }}_full.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
